Accept slower results

diff --git a/.github/workflows/benchmarks.yml b/.github/workflows/benchmarks.yml
--- a/.github/workflows/benchmarks.yml
+++ b/.github/workflows/benchmarks.yml
@@ -33,7 +33,8 @@ jobs:
       - name: Run benchmarks
         run: |
           conda run -n test asv machine --yes
-          conda run -n test asv continuous HEAD^ HEAD
+          # Don't return exit code 1 if results are slower
+          conda run -n test asv continuous HEAD^ HEAD || true;
 
       - name: Checkout benchmarks
         run: |
